<a href="https://colab.research.google.com/github/trisha123789/Transformer/blob/main/Transformers_core_understanding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
import torch.nn as nn

In [ ]:
embed = nn.Embedding(10,4)

In [ ]:
x = torch.tensor([
    [1, 0, 1, 0],
    [0, 1, 0, 1],
    [1, 1, 1, 1]
])

In [ ]:
print(embed(x))

tensor([[[ 0.3868, -0.8293, -0.2331, -1.3468],
         [ 1.4482, -0.0700, -0.3114, -1.0899],
         [ 0.3868, -0.8293, -0.2331, -1.3468],
         [ 1.4482, -0.0700, -0.3114, -1.0899]],

        [[ 1.4482, -0.0700, -0.3114, -1.0899],
         [ 0.3868, -0.8293, -0.2331, -1.3468],
         [ 1.4482, -0.0700, -0.3114, -1.0899],
         [ 0.3868, -0.8293, -0.2331, -1.3468]],

        [[ 0.3868, -0.8293, -0.2331, -1.3468],
         [ 0.3868, -0.8293, -0.2331, -1.3468],
         [ 0.3868, -0.8293, -0.2331, -1.3468],
         [ 0.3868, -0.8293, -0.2331, -1.3468]]], grad_fn=<EmbeddingBackward0>)


# here nn is neural network ans embeddings(vector size,dimensions) 1,2,3 can be ids

In [ ]:
scores = torch.matmul(x,x.T)


In [ ]:
weights = torch.softmax(scores.float(),dim=-1)

In [ ]:
output = torch.matmul(weights,x.float())

In [ ]:
output

tensor([[0.9366, 0.5317, 0.9366, 0.5317],
        [0.5317, 0.9366, 0.5317, 0.9366],
        [0.8935, 0.8935, 0.8935, 0.8935]])

similarity(q,k)=q⋅k

transformers relate which two word vectors are similar we use dot products

In [ ]:
import torch

In [ ]:
k  = torch.tensor([1.,2.,3.])

In [ ]:
k1 = torch.tensor([1.,2.,3.])

In [ ]:
k2 = torch.tensor([-1.,0.,1.])

In [ ]:
v1 = torch.dot(k,k1)

In [ ]:
v2 = torch.dot(k,k2)

In [ ]:
print(v1)

tensor(14.)


In [ ]:
print(v2)

tensor(2.)


therefore,we must conclude that if the value of the ot product is more than the similarity between thew words is more or else it is less

<h3>but this is not the actual thing we will scale it by dividing by sqrt(dk) </h3>
<ul>
<li>so we might have large number of dimensions and we are doing dot product
</li>
<li> so the softmax becomes too sharp we dont want it so wee will scale it
</li>
</ul>


In [ ]:
d_k = k.shape[0]

In [ ]:
v1 = torch.dot(k,k1)/torch.sqrt(torch.tensor(d_k,dtype=torch.float))

In [ ]:
print(v1)

tensor(8.0829)


In [ ]:
v2 = torch.dot(k,k2)/torch.sqrt(torch.tensor(d_k,dtype=torch.float))

In [ ]:
print(v2)

tensor(1.1547)


SOFTMAX--ATTENTION DISTRIBUTION

In [ ]:
scores = torch.tensor([2.0,1.0,0.0])

In [ ]:
weights = torch.softmax(scores,dim=0)

In [ ]:
print(weights)

tensor([0.6652, 0.2447, 0.0900])


In [ ]:
print(weights.sum())

tensor(1.)


here the sum of all the probabilities will be equal to 1

In [ ]:
#single head attention

In [ ]:
def self_attention(K,Q,V):
  d_k = Q.shape[-1]
  # to get the embedding dimension shape
  scores = torch.matmul(Q,K.T)/torch.sqrt(torch.tensor(d_k,dtype=torch.float))
  weights = torch.softmax(scores,dim=-1)
  return torch.matmul(weights,V)

In [ ]:
Q = torch.tensor([[1.0,0.0],[0.0,1.0],[1.0,1.0]])

In [ ]:
K = Q

In [ ]:
V = Q

In [ ]:
self_attention(K,Q,V)

tensor([[0.8022, 0.5989],
        [0.5989, 0.8022],
        [0.7517, 0.7517]])

In [ ]:
scores = torch.tensor([[1.0,2.0,3.0],[1.0,2.0,3.0],[1.0,2.0,3.0]])

In [ ]:
mask = torch.tril(torch.ones(3,3))

In [ ]:
scores = scores.masked_fill(mask==0,float('inf'))

In [ ]:
weights = torch.softmax(scores,dim=-1)

In [ ]:
print(weights)

tensor([[   nan,    nan,    nan],
        [   nan,    nan,    nan],
        [0.0900, 0.2447, 0.6652]])


In [73]:
import math
def positional_encoding(pos, d):
  pe = []
  for i in range(d):
     if i % 2 == 0:
      pe.append(math.sin(pos / (10000 ** (i/d))))
     else:
      pe.append(math.cos(pos / (10000 ** ((i-1)/d))))
  return torch.tensor(pe)
print(positional_encoding(1, 6))

tensor([0.8415, 0.5403, 0.0464, 0.9989, 0.0022, 1.0000])
